### ISSUE TITLE
How customStorage methods are invoked

### ISSUE THREAD

**Issue by himasimplisafe** [arthurfiorette/axios-cache-interceptor#174]
After setupCache with customStorage, how these find, set, remove methods are invoked, I couldn't see any explanation in 
https://axios-cache-interceptor.js.org/#/pages/storages.
Is it first going to check if key exists using find and then return if it is cached, otherwise sets cache?

**Comment by arthurfiorette** [comment]
> Is it first going to check if key exists using find and then return if it is cached, otherwise sets cache?

Tt's really more complicated than that. It's literally the whole interceptor logic...

Well, the `find`, `set` and `remove` methods are wrapped by the `buildStorage` function, it returns a `AxiosStorage` object that is called in the whole code.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f25bff6d1c1bdf46829be3cb3ee6995716246b2c/src/storage/build.ts#L58

**Comment by arthurfiorette** [comment]
If you understand axios, you'll see that this plugin works by applying a interceptor before every request and before every response. The [request interceptor](https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/src/interceptors/request.ts) can be considered the "main" entry for this code.

Inside the request interceptor's `onFulfilled` property, you can see all checks and executed logic for each call to the cache interceptor.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/f25bff6d1c1bdf46829be3cb3ee6995716246b2c/src/interceptors/request.ts#L17

If it was simple as _"going to check if key exists using find and then return if it is cached, otherwise sets cache"_, a lot of requests would be cached (or not) incorrectly.

Right now, it caches the first response, than returns this cached response until the cache becomes stale. And then, it checks for the cache TTL, Etag, many request headers and more small things to see if the request can be reused / revalidated.

**Comment by arthurfiorette** [comment]
A good resource to learn and understand a bit better, is the PR for implementation of `Etag`, you can read #49 and #53.

**Comment by arthurfiorette** [comment]
And yes, I could create a flowchart_(or something similar)_ to represent all possible behaviours.
But, as there are many options and completely different behaviours, or I'll need to create a lot of charts or there will be a giant bloated chart that nobody understands.

Other than that I don't know how to make good flowcharts :p

**Comment by himasimplisafe** [comment]
Ok, if we have `ttl` to expire the cache, why we need `remove` method?

**Comment by himasimplisafe** [comment]
In `[axios-cache-interceptor/src/storage/build.ts](https://github.com/arthurfiorette/axios-cache-interceptor/blob/f25bff6d1c1bdf46829be3cb3ee6995716246b2c/src/storage/build.ts#L58)`, i have put logs to see if flow is going to buildStorage method, but logs haven't printed

**Comment by arthurfiorette** [comment]
You added console.logs on typescript files?

The actual code that is executed is a transpiled and minified javascript file from all `src/**` files.

**Comment by arthurfiorette** [comment]
> Ok, if we have ttl to expire the cache, why we need remove method?

Because the cache doesn't remove itself. When the interceptor realize that the TTL expired, it will call the `remove` method.

**Comment by arthurfiorette** [comment]
@himasimplisafe can I close this issue?

**Comment by himasimplisafe** [comment]
Sure, when you get chance, it would be nice to put some documentation or Diagram or flow charts to explain how customStorage works
