### ISSUE TITLE
How to force update a cached request that has a long TTL?

### ISSUE THREAD

**Issue by aballet** [arthurfiorette/axios-cache-interceptor#177]
Hi,

I'm in the following situation: I have some requests that I'd like to cache for as long as possible, so I set a very long TTL, because my users might not be connected to the Internet for a long time. However, once in a while, I update the content, and I want to enable the users to fetch the new content whenever they are connected.

How can I force update a response? I know I can disable the cache with the cache:false option so that the users will be served a fresh version of the response, but from what I understand, the cache will be completely bypassed, i.e. the new response will not be saved locally, is that correct? If so, is there a way to force that behavior?

I thought about deleting the entry from the storage first, but that's a bit dangerous because if the request goes wrong, then the local version will be deleted, and I won't have a fresh version to replace it.

Many thanks for your hard work on this project!

**Comment by arthurfiorette** [comment]
Hmm, I think that you can achieve that with the following:

Enable Etag (or If-Modified-Since) to indicate that a new content is available. This also means that you server should return a Etag or If-Modified-Since. And enable `staleIfError` with a short TTL value.

This way the interceptor will serve the content while valid, then if stale, it will send a new request  that listen for [304 statuses (with empty responses)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) and in case of a network error (you can filter these errors with `StaleIfErrorPredicate`), the cache will be used.

I guess that with the "modern cache" standarts, this will be the closest to it without a bit of coding...

**Comment by aballet** [comment]
I understand now how staleIfErrof world, thank you for the explanation, I managed to do what I wanted following your suggestion. 🥳

**Comment by arthurfiorette** [comment]
Alright, can I close this issue?
