### ISSUE TITLE
feature request: cache override/force

### ISSUE THREAD

**Issue by domdomegg** [arthurfiorette/axios-cache-interceptor#256]
It'd be useful to have an option on making a request to clear the existing cache for the id. This is because knowing the id of a request to invalidate it can be difficult.

The workaround I might use for now is to use the built in id generator and calculate the expected id from it, but it adds a lot of complexity.

I see this being implemented as:
1. calculate `id` using the key generator
2. calling `await axios.storage.remove(id)`
3. running the request

**Comment by domdomegg** [comment]
NB: Setting `cache` to `false` doesn't do what we want here, because that then doesn't update the cache for future requests that we want to use the cache.

**Comment by arthurfiorette** [comment]
Hey @domdomegg, this can be a feature implemented...

But why can't you force a custom request I'd for that?

**Comment by domdomegg** [comment]
In my react application I might have many places that call the same API. I'd have to syncronise the request id across all of them to get the caching to work properly, so I'd prefer the autogenerated ids.

**Comment by arthurfiorette** [comment]
Hey @domdomegg, with what you've said to me, seems that you need to externalize and centralize all request functions into a more stable file, so you just have to use your `createUser()` function instead of calling `user.create` everywhere. *(example)*.

However, this is also a pretty solid and valid feature to have, so I have just implemented that anyways.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/docs/pages/per-request-configuration.md#cacheoverride

If everything is good, i can release a patch version with it. (I'm waiting axios 1.0, to this project be semver compliant)

**Comment by domdomegg** [comment]
Hey @arthurfiorette, the `override` option you've implemented exactly what I wanted I think - thanks :raised_hands:

I agree that centralizing all request functions might go some way to alleviating this problem. However, in our app doing that would add quite a bit of boilerplate to an app that already strictly types its APIs using some existing wrappers. And yes, those wrappers could also generate unique ids for each endpoint and make sure it's applying them correctly when calling with different arguments/params etc. (I think the same might go for a file which externalizes and centralizes the right ids dependent on params etc.), but at least in our codebase that would be significantly more complex than being able to override the cache when making certain requests we know shouldn't use the cache anyways.

Again, thanks for the amazingly fast response - this feature really helps us :)

**Comment by arthurfiorette** [comment]
Alright! I'll release it tomorrow. Thanks again!

**Comment by arthurfiorette** [comment]
Hey @domdomegg, I've just released 0.10.5!
