### ISSUE TITLE
The plugin is not working, not sure where it went wrong.

### ISSUE THREAD

**Issue by apt-frontend** [arthurfiorette/axios-cache-interceptor#277]
My main axios file where i create axios instance
----------------------------------------------------------------------------------------
https://pastebin.com/PFz8SvrV

This is my services/repository
https://pastebin.com/7NZxAHwa
Now when i navigate from one page to another and come back to old one, there always new get request, maybe the setup i have done is not proper

**Comment by arthurfiorette** [comment]
Please, can you format the code you've post with ```?

**Comment by apt-frontend** [comment]
I am stuggling with it but let me provide you ss instead

**Comment by arthurfiorette** [comment]
> I am stuggling with it but let me provide you ss instead

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by apt-frontend** [comment]
```https://stackblitz.com/edit/nextjs-crs2eb?file=package.json,middleware%2Faxios.js,services%2Fposts.js,pages%2Findex.js```
Nope this is also not working, and also the debug option is not working.
I have added mini version of my project

**Comment by arthurfiorette** [comment]
First of all, the debug mode is not working because, as the [documentation](https://axios-cache-interceptor.js.org/#/pages/development-mode) says, you need to import it from `axios-cache-interceptor/dev` to make it work.

In my tests the request is being cached. 

You defined `ttl: 0` which tell the interceptor that any cache should only live for about 0 milliseconds... But that isn't the final behavior, because the `interpretHeader` option is true by default. It chooses to use any information, if available, in the `cache-control` response header to define its ttl. [Read more about header interpretation.](https://axios-cache-interceptor.js.org/#/pages/per-request-configuration?id=cacheinterpretheader)

You can see that the response returned a Cache Control with `max-age=43200`:

![image](https://user-images.githubusercontent.com/47537704/175087742-09664046-9ce6-4e96-81fe-b0cb806fc7f4.png)

**Comment by apt-frontend** [comment]
Thank you
