### ISSUE TITLE
Feature Suggestion: Gimme "Stale cache"

### ISSUE THREAD

**Issue by sbscan** [arthurfiorette/axios-cache-interceptor#469]
I used to use Fetch and some state management library as you said. And now switch to your great library but only one function is missing from my own use.

For slow networks, I usually show old data and if data not loaded in 1 sec, I inform the user and still load in the background. When finish laoding simply show fresh data. This is a very practical way becasue I don't interrupt user, maybe even he/she doesn't need the new data.

I think it would be great if I could pass a callback and it gives me stale cache data. When fresh data is pulled, it will call my callback and I'll get my new fresh data.

Maybe sounds wierd, but really is cool for slow networks.

**Comment by arthurfiorette** [comment]
Hey @sbscan, neat idea! I thought something similar before but let it go because I was trying to hack something togheter with promises and it didn't work... The problem was in the instant axios request is resolved with cached data, I couldn't resolve it again with the newer requested one.

In the request interceptor, if we change the adapter to resolve with cache data, as we do below, there's no way to tell axios to proceed with the request and fetch it remotely.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/a139c337ec5a640b9d1a1c605a0000f435c7fe18/src/interceptors/request.ts#L197-L206

Because or we return the config in the request interceptor, and at the end axios calls the underlying adapter (`XMLHttpRequest`) or we update the adapter to be just a `() => Promise.resolve(DATA)` and return what we want without any external call.

**Comment by arthurfiorette** [comment]
Using a callback option in the config we can end up with two possibilites:

1. Return the axios promises with cache first data and use a callback for when the network call finishes.
2. Resolve the promise whenever the network call ended and may call the _callback_ first with cache data.

Option 1 won't work because of inconsistencies, like when you don't have any cache to resolve the promise first and have to wait the network call, leading the callback and the promise being resolved in the same time and a possible double render in your app.

Leading us the second option, which kindly is what we have today, but witha direct call to the storage first.

You can achieve this today with this example code:

```ts
const KEY = 'my key';

const cache = await axios.storage.get(KEY);

if (cache.state !== 'empty') {
  render(cache.data);
}

const response = await axios.get('url with data', {
  cache: {
    override: true // always request, no matter if the cache has it
  }
})

if (response.status === 200) {
  render(response.data);
}
```

**Comment by arthurfiorette** [comment]
Thinking more in terms of API design, what do you thing to allow the `override` parameter to also allow a callback to receive cache data, if present...

```ts
// will just ignore the current cache and request it again
axios.get('url', {
  cache: {
    override: true
  }
})

// Still requests through the network no matter what but calls the
// override callback right know if we have something valid in the cache.
axios.get('url', {
  cache: {
    override: (currentCache) => {
      temporaryRender(currentCache)
    }
  }
})
```

I don't know yet if this use case (that can be done manually) should be added into the API, neither inside the `override` parameter.

**Comment by arthurfiorette** [comment]
[Apollo has something similar ](https://www.apollographql.com/docs/react/data/queries/#cache-and-network)

**Comment by sbscan** [comment]
First thanks for this reply. BTW I'm coding for long time without sleep, so my brain slow down, later I'll read again but I think you misunderstood me. Think of customers endpoint, we have old data in cache but expired. When I fetch it, I want to get the expired data from the cache immediately and then with the help of a call back I could get most recent data. I'll explain why I need this:
Think of 20-30k customers and a slow network. The customers data is already in memory of browser. The user click customers and expired customer data immediately appears on the screen. So user is happy 'coz not waiting in even slow network. After some time, 1 sec as example, I notice user that data is still loading, and when new fresh data arrives that loading notice disappear and user knows data refreshed.
This is a non-blocking experience like our lovely JavaScript.

**Comment by arthurfiorette** [comment]
That's what I was trying to exemplify :) It's late at night and I drank a lot today...

We cannot resolve 2 times the same promise that `axios.get` returns, e.g. to mimic the behavior or resolving with cache first and later resolving it again with network data, that's why callbacks. 
Here's a detailed example for the second option above.

```ts
async function getData(callback: (data: any) => void) {
  // Simple key to sync the storage call with the axios call
  const KEY = 'my request key';
  
  // This promise in the storage, unless you are using
  // a custom storage, will resolve immediately.
  const cache = await axios.storage.get(KEY);
  
  // calls with cache data
  if (cache.state !== 'empty') {
    callback(cache.data);
  }
  
  // user is already happy with cached data, now lets see if we can get a newer one.
  const response = await axios.get('url with data', {
    id: KEY,
    cache: {
      override: true // always request, no matter if the cache has it
    }
  })
  
  // response wasn't cached, so server returned a newer one, lets call the callback again
  if (!response.cached) {
    callback(response.data);
  }
}

// and then
getData(data => {
  console.log(data);
})

// Will print the cached version shortly after and, when the network response arrives,
// print the newer one. Just exactly as you need.
```

**Comment by sbscan** [comment]
Don't drink and code :) I think better method would be like this:
If you can give me proxy of the cache for my particular endpoint, I can use the stale data from proxy and show the old data to user. When fetch is finished the proxy will be updated automatically and so my table.  I think this way is simple, I use this method in my projects. What do you think?

**Comment by arthurfiorette** [comment]
> If you can give me proxy of the cache for my particular endpoint, 

What do you mean by proxy of the cache?

If I could understand it right, this data-proxy between axios and your code, where it is updated from various sources is something that needs to be abstracted in your code. It is way out of scope for an axios general library related to caching between axios calls and network, and not between a custom interface and axios calls.

What you can do is use the axios storage in the same architectural way of your proxy, you search in 
 it, run an axios request and search again in the storage, this way you'll only have to implement one way of getting data and the `axios.get` call will automatically update the response in the cache.

You can achieve that by creating a custom storage with events, like `myStorage.onData(KEY, (data) => { /* code */})` and calling `axios.get` whenever you want to and the onData callback will be automatically ran.

**Comment by arthurfiorette** [comment]
Hey @sbscan, anything else?

I added the below idea to my todo list and will do as soon as I can.

> Thinking more in terms of API design, what do you thing to allow the `override` parameter to also allow a callback to receive cache data, if present...
> 
> ```ts
> // will just ignore the current cache and request it again
> axios.get('url', {
>   cache: {
>     override: true
>   }
> })
> 
> // Still requests through the network no matter what but calls the
> // override callback right now if we have something valid in the cache.
> axios.get('url', {
>   cache: {
>     override: (currentCache) => {
>       temporaryRender(currentCache)
>     }
>   }
> })
> ```
> 
> I don't know yet if this use case (that can be done manually) should be added into the API, neither inside the `override` parameter.
