### ISSUE TITLE
DOMException: A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by CatchABus** [arthurfiorette/axios-cache-interceptor#530]
In Firefox private window, I receive the following exception when trying to load my app.
```
DOMException: A mutation operation was attempted on a database that did not allow mutations.
```

I use a custom storage based on indexedDb and it seems there are missing try-catch clauses for `find` and `set` (even though the latter is nested inside one).
I think it'd be safer if we caught exceptions for all storage overridden methods (`find`, `set`, `remove`, and so on).

**Comment by arthurfiorette** [comment]
You are running into this error because of your custom storage accessing indexedDb right?
Why you can't add a try catch in your implementations, since this is a custom-storage implementation error?
We cannot proceed without storage anywhere we need it, so any possible try catch would just re-throw the error...
