### ISSUE TITLE
Does this work in a multi-process environment?

### ISSUE THREAD

**Issue by mahnunchik** [arthurfiorette/axios-cache-interceptor#925]
### What happened?

I quickly ran through the code and it looks like the module will not work correctly with cache if used with persistent storage (Redis for example https://axios-cache-interceptor.js.org/guide/storages#node-redis-storage) in a multi-process environment.

### axios-cache-interceptor version

1.6.1

### Node / Browser Version

20

### Axios Version

1.7.7

### What storage is being used

Another one

### Relevant debugging log output

```js
-
```

**Comment by arthurfiorette** [comment]
What are your assumptions on why this wouldn't work in a multi process environment? The only thing that shouldn't work is request deduplication when each of them are being used in a different process.

**Comment by mahnunchik** [comment]
@arthurfiorette Exactly this case! Identical simultaneous requests from 2+ processes.

It looks like in the current implementation the second+ request will fail with an error.

**Comment by arthurfiorette** [comment]
Since the `waiting` list is now just a promise map that resolves with nothing, that could chance to an event emitter interface that could be extended by your redis instance to emit events real time.

Are you up to a PR? remember to add unit tests.

[This PR will be a good read](https://github.com/arthurfiorette/axios-cache-interceptor/commit/a7a4e31e573a50fe38309809acd037fb3448040b)

**Comment by mahnunchik** [comment]
Actually I'm working with MongoDB as a storage provider, there is no simple way to emit event between instances.

**Comment by arthurfiorette** [comment]
if your storage provider isn't capable of sending/receiving events, there's not much we would be able to do anyways...
