### ISSUE TITLE
Unusable in scenarios where no axios reference is available

### ISSUE THREAD

**Issue by gryphonmyers** [arthurfiorette/axios-cache-interceptor#99]
I would like to try this package, but as implemented, using `setupCache` necessitates a reference to the axios instance. Unfortunately, in some use cases no such reference exists. For example, some packages wrap axios and pass through configuration to the axios instance, but do not expose the instance itself (e.g. https://www.npmjs.com/package/contentful).

I would suggest making these use cases possible by allowing the cache to passed into the `adapter` option of axios.

**Comment by arthurfiorette** [comment]
Hi! This package uses interceptors, not adapters _(the name says that 😁)_ and that's why this package is so modular.

I don't understand exactly what you're trying to exemplify, but if you look at the `setupCache` function, you'll see that it's very simple to add "cache" logic to any instance of axios.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/e6a9d1223a2fd8d363686d5bbceae39b288099dc/src/cache/create.ts#L60-L90

This means that the given "axios" instance is returned from the **function and can also be the global**.

It's kind of weird that in the content example they don't allow you to touch the axios stuff and apparently they don't use the default one.

https://github.com/contentful/contentful-sdk-core/blob/672cbadcab2078793be8ee5b3c182d695ac72549/src/create-http-client.ts#L115

That way it's kind of hard to apply the interceptor. You told that you have access to use a custom adapter, so I assume you can apply an interceptor as well, by manually writing what is in the `useCache` function. 

If you know the code snippet that creates axios with `axios.create` (or any other function), you can also wrap the `AxiosStatic#create` function in something like this:

```js
import axios from 'axios';
import { createClient } from 'contentful';

// UNTESTED!

const oldCreate = axios.create;

axios.create = (...params) => {
  const axios = oldCreate(...params);

  // Apply the cache
  setupCache(axios);
  
  // Revert the default function
  axios.create = oldCreate;

  return axios;
}

// call the function that uses axios.create

createClient(/* ... */);
```

This way, when the `createClient` function internally calls the `axios.create` function, it will execute the above function and clean itself so that the next call doesn't break anything.

I'm sorry this seems like the only option for you, but it looks like a design flaw in the library you're using. If you need more help implementing the above, just ask here and I will help.

**Comment by gryphonmyers** [comment]
I see so the problem here is you're not actually using the 'adapter' feature at all. You're using a different axios feature altogether (I was not aware that 'interceptors' were a specific axios feature). It's kind of lame that interceptors can only be interacted with imperatively.

I don't necessarily disagree regarding contentful's client being... Not so well thought out. Even so, other axios caching solutions are capable of supporting both patterns. They just have a lot of other problems as well. It may be I just need to create yet another caching solution for this ecosystem 😆

**Comment by arthurfiorette** [comment]
Right... The adapter is meant to do the request, and interceptors to manage, recycle, prevent and etc. Why you can use adapters and not interceptors?

Unless you're selecting to intercept each request, _(`api.get('url', {adapter:custom adapter})`)_, where you can get access to some kind of wrapper, the usage should be the same.

Still, there are only 2 ways the unavailable instance was created: From global or from `Axios#create`. If it's global, you can just set it globally. If it's created from `Axios#create`, you can override this function just once to apply the cache as well.

Anyways, sorry that i couldn't help more with this package.

**Comment by gryphonmyers** [comment]
> Right... The adapter is meant to do the request, and interceptors to manage, recycle, prevent and etc. Why you can use > > adapters and not interceptors?

Because there is no instantiation option for interceptors. As I say, they can only be created imperatively, which requires a reference to the axios instance. Contentful's client lets me configure the instantiation of the axios instance, but they do not provide a reference to the instance once it has been instantated.

In any case, I'm going to figure this out using a different solution. Since this problem is out of scope for what you're trying to accomplish with your package, I'll close the issue. Thanks!
